In [1]:
import pandas as pd
import numpy as np
from collections import Counter
import time
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import cross_validate, cross_val_predict
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.under_sampling import CondensedNearestNeighbour, RandomUnderSampler


In [2]:
_data = pd.read_csv('./data/Modelar_UH2020.txt', sep='|')
_labels = _data.CLASE
_data.drop('CLASE', axis=1, inplace=True)
_data.drop('ID', axis=1, inplace=True)

# Variable categórica a numérica:
_data['CADASTRALQUALITYID'] = _data['CADASTRALQUALITYID'].map({'9': 0,
                               '8': 1,
                               '7': 2,
                               '6': 3,
                               '5': 4,
                               '4': 5,
                               '3': 6,
                               '2': 7,
                               '1': 8,
                               'C': 9,
                               'B': 10,
                               'A': 11})

# Imputación de NANs con la mediana:
_data['MAXBUILDINGFLOOR'].fillna(_data['MAXBUILDINGFLOOR'].median(), inplace=True)
_data['CADASTRALQUALITYID'].fillna(_data['CADASTRALQUALITYID'].median(), inplace=True)

#### Normalizar:

In [3]:
_data = pd.DataFrame( MinMaxScaler().fit_transform(_data), columns=_data.columns)
#_data = pd.DataFrame( StandardScaler().fit_transform(_data), columns=_data.columns)

## AGRICULTURE vs RETAIL:

In [5]:
data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "RETAIL"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values
print(Counter(y))
print()
cv_results = cross_validate(RandomForestClassifier(n_jobs=-1), X, y, cv=3)
print(cv_results['test_score'])
cv_pred = cross_val_predict(RandomForestClassifier(n_jobs=-1), X, y, cv=3)
print(classification_report(y, cv_pred, digits=3))

Counter({'RETAIL': 2093, 'AGRICULTURE': 338})

[0.97780518 0.96790123 0.98148148]
              precision    recall  f1-score   support

 AGRICULTURE      0.922     0.905     0.913       338
      RETAIL      0.985     0.988     0.986      2093

    accuracy                          0.976      2431
   macro avg      0.953     0.946     0.950      2431
weighted avg      0.976     0.976     0.976      2431



In [6]:
data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "RETAIL"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values

model = RandomForestClassifier(n_jobs=-1)
feature_square(data, labels, model)

data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "RETAIL"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values

model = RandomForestClassifier(n_jobs=-1)
feature_selection(data, labels, model)

Punto de partida(todas las características) 0.9773755656108597
Añadimos:  X2 , Resultado:  0.9794323323735088
-------------->  X2   mejora:  0.002056766762649098
Añadimos:  Y2 , Resultado:  0.9777869189633895
-------------->  Y2   mejora:  0.00041135335252984184
Añadimos:  Q_R_4_0_02 , Resultado:  0.9790209790209791
-------------->  Q_R_4_0_02   mejora:  0.0016454134101193674
Añadimos:  Q_R_4_0_12 , Resultado:  0.9781982723159194
-------------->  Q_R_4_0_12   mejora:  0.0008227067050596837
Añadimos:  Q_R_4_0_22 , Resultado:  0.9777869189633895
-------------->  Q_R_4_0_22   mejora:  0.00041135335252984184
Añadimos:  Q_R_4_0_32 , Resultado:  0.9781982723159194
-------------->  Q_R_4_0_32   mejora:  0.0008227067050596837
Añadimos:  Q_R_4_0_42 , Resultado:  0.9794323323735088
-------------->  Q_R_4_0_42   mejora:  0.002056766762649098
Añadimos:  Q_R_4_0_52 , Resultado:  0.9794323323735088
-------------->  Q_R_4_0_52   mejora:  0.002056766762649098
Añadimos:  Q_R_4_0_62 , Resultado:  0.9790

Añadimos:  Q_NIR_8_0_52 , Resultado:  0.9786096256684492
Añadimos:  Q_NIR_8_0_62 , Resultado:  0.9769642122583299
Añadimos:  Q_NIR_8_0_72 , Resultado:  0.9773755656108597
Añadimos:  Q_NIR_8_0_82 , Resultado:  0.9790209790209791
Añadimos:  Q_NIR_8_0_92 , Resultado:  0.9786096256684492
Añadimos:  Q_NIR_8_1_02 , Resultado:  0.9781982723159194
Añadimos:  AREA2 , Resultado:  0.9798436857260386
Añadimos:  GEOM_R12 , Resultado:  0.9786096256684492
Añadimos:  GEOM_R22 , Resultado:  0.9786096256684492
Añadimos:  GEOM_R32 , Resultado:  0.9765528589058001
Añadimos:  GEOM_R42 , Resultado:  0.9790209790209791
Añadimos:  CONTRUCTIONYEAR2 , Resultado:  0.9765528589058001
Añadimos:  MAXBUILDINGFLOOR2 , Resultado:  0.9786096256684492
Añadimos:  CADASTRALQUALITYID2 , Resultado:  0.9777869189633895
Añadimos:  Q_B_2_0_922 , Resultado:  0.9786096256684492
===========> Añadimos:  Q_G_3_0_12  --------------> score:  0.9802550390785685
 
Añadimos:  X2 , Resultado:  0.9790209790209791
Añadimos:  Y2 , Resultado

Eliminanmos:  Q_B_2_0_8
Eliminanmos:  Q_B_2_0_9
Eliminanmos:  Q_B_2_1_0
Eliminanmos:  Q_NIR_8_0_0
Eliminanmos:  Q_NIR_8_0_1
Eliminanmos:  Q_NIR_8_0_2
Eliminanmos:  Q_NIR_8_0_3
Eliminanmos:  Q_NIR_8_0_4
Eliminanmos:  Q_NIR_8_0_5
Eliminanmos:  Q_NIR_8_0_6
Eliminanmos:  Q_NIR_8_0_7
Eliminanmos:  Q_NIR_8_0_8
Eliminanmos:  Q_NIR_8_0_9
Eliminanmos:  Q_NIR_8_1_0
Eliminanmos:  AREA
Eliminanmos:  GEOM_R1
Eliminanmos:  GEOM_R2
Eliminanmos:  GEOM_R3
Eliminanmos:  CONTRUCTIONYEAR
Eliminanmos:  MAXBUILDINGFLOOR
Eliminanmos:  CADASTRALQUALITYID


## AGRICULTURE vs PUBLIC:

In [6]:
data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "PUBLIC"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values
print(Counter(y))
print()
cv_results = cross_validate(RandomForestClassifier(n_jobs=-1), X, y, cv=3)
print(cv_results['test_score'])
cv_pred = cross_val_predict(RandomForestClassifier(n_jobs=-1), X, y, cv=3)
print(classification_report(y, cv_pred, digits=3))

Counter({'PUBLIC': 2976, 'AGRICULTURE': 338})

[0.97828054 0.97918552 0.97282609]
              precision    recall  f1-score   support

 AGRICULTURE      0.894     0.852     0.873       338
      PUBLIC      0.983     0.989     0.986      2976

    accuracy                          0.975      3314
   macro avg      0.939     0.920     0.929      3314
weighted avg      0.974     0.975     0.974      3314



In [7]:
data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "PUBLIC"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values

model = RandomForestClassifier(n_jobs=-1)
feature_square(data, labels, model)

data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "PUBLIC"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values

model = RandomForestClassifier(n_jobs=-1)
feature_selection(data, labels, model)

Punto de partida(todas las características) 0.9788774894387448
Añadimos:  X2 , Resultado:  0.9770669885334943
Añadimos:  Y2 , Resultado:  0.9767652383826192
Añadimos:  Q_R_4_0_02 , Resultado:  0.9779722389861195
Añadimos:  Q_R_4_0_12 , Resultado:  0.9776704888352444
Añadimos:  Q_R_4_0_22 , Resultado:  0.9782739891369946
Añadimos:  Q_R_4_0_32 , Resultado:  0.9764634882317441
Añadimos:  Q_R_4_0_42 , Resultado:  0.9782739891369946
Añadimos:  Q_R_4_0_52 , Resultado:  0.9779722389861195
Añadimos:  Q_R_4_0_62 , Resultado:  0.975859987929994
Añadimos:  Q_R_4_0_72 , Resultado:  0.976161738080869
Añadimos:  Q_R_4_0_82 , Resultado:  0.9791792395896198
-------------->  Q_R_4_0_82   mejora:  0.0003017501508750797
Añadimos:  Q_R_4_0_92 , Resultado:  0.9770669885334943
Añadimos:  Q_R_4_1_02 , Resultado:  0.9773687386843694
Añadimos:  Q_G_3_0_02 , Resultado:  0.9773687386843694
Añadimos:  Q_G_3_0_12 , Resultado:  0.9788774894387448
Añadimos:  Q_G_3_0_22 , Resultado:  0.9773687386843694
Añadimos:  Q_G

Eliminanmos:  Q_R_4_0_3
Eliminanmos:  Q_R_4_0_4
Eliminanmos:  Q_R_4_0_5
Eliminanmos:  Q_R_4_0_6
Eliminanmos:  Q_R_4_0_7
Eliminanmos:  Q_R_4_0_8
Eliminanmos:  Q_R_4_0_9
Eliminanmos:  Q_R_4_1_0
Eliminanmos:  Q_G_3_0_0
Eliminanmos:  Q_G_3_0_1
Eliminanmos:  Q_G_3_0_2
Eliminanmos:  Q_G_3_0_3
Eliminanmos:  Q_G_3_0_4
Eliminanmos:  Q_G_3_0_5
Eliminanmos:  Q_G_3_0_6
Eliminanmos:  Q_G_3_0_7
Eliminanmos:  Q_G_3_0_8
Eliminanmos:  Q_G_3_0_9
Eliminanmos:  Q_B_2_0_0
Eliminanmos:  Q_B_2_0_1
Eliminanmos:  Q_B_2_0_2
Eliminanmos:  Q_B_2_0_3
Eliminanmos:  Q_B_2_0_4
Eliminanmos:  Q_B_2_0_5
Eliminanmos:  Q_B_2_0_6
Eliminanmos:  Q_B_2_0_7
Eliminanmos:  Q_B_2_0_8
Eliminanmos:  Q_B_2_0_9
Eliminanmos:  Q_B_2_1_0
Eliminanmos:  Q_NIR_8_0_0
Eliminanmos:  Q_NIR_8_0_1
Eliminanmos:  Q_NIR_8_0_2
Eliminanmos:  Q_NIR_8_0_3
Eliminanmos:  Q_NIR_8_0_4
Eliminanmos:  Q_NIR_8_0_5
Eliminanmos:  Q_NIR_8_0_6
Eliminanmos:  Q_NIR_8_0_7
Eliminanmos:  Q_NIR_8_0_8
Eliminanmos:  Q_NIR_8_0_9
Eliminanmos:  Q_NIR_8_1_0
Eliminanmos:  AREA

## AGRICULTURE vs OTHER:

In [7]:
data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "OTHER"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values
print(Counter(y))
print()
cv_results = cross_validate(RandomForestClassifier(n_jobs=-1), X, y, cv=3)
print(cv_results['test_score'])
cv_pred = cross_val_predict(RandomForestClassifier(n_jobs=-1), X, y, cv=3)
print(classification_report(y, cv_pred, digits=3))

Counter({'OTHER': 1332, 'AGRICULTURE': 338})

[0.97127469 0.98025135 0.97122302]
              precision    recall  f1-score   support

 AGRICULTURE      0.933     0.950     0.941       338
       OTHER      0.987     0.983     0.985      1332

    accuracy                          0.976      1670
   macro avg      0.960     0.966     0.963      1670
weighted avg      0.976     0.976     0.976      1670



In [8]:
data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "OTHER"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values

model = RandomForestClassifier(n_jobs=-1)
feature_square(data, labels, model)

data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "OTHER"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values

model = RandomForestClassifier(n_jobs=-1)
feature_selection(data, labels, model)

Punto de partida(todas las características) 0.9754491017964072
Añadimos:  X2 , Resultado:  0.9790419161676647
-------------->  X2   mejora:  0.003592814371257469
Añadimos:  Y2 , Resultado:  0.9784431137724551
-------------->  Y2   mejora:  0.0029940119760478723
Añadimos:  Q_R_4_0_02 , Resultado:  0.9772455089820359
-------------->  Q_R_4_0_02   mejora:  0.001796407185628679
Añadimos:  Q_R_4_0_12 , Resultado:  0.9772455089820359
-------------->  Q_R_4_0_12   mejora:  0.001796407185628679
Añadimos:  Q_R_4_0_22 , Resultado:  0.9754491017964072
Añadimos:  Q_R_4_0_32 , Resultado:  0.9754491017964072
Añadimos:  Q_R_4_0_42 , Resultado:  0.974251497005988
Añadimos:  Q_R_4_0_52 , Resultado:  0.9766467065868264
-------------->  Q_R_4_0_52   mejora:  0.0011976047904191933
Añadimos:  Q_R_4_0_62 , Resultado:  0.9772455089820359
-------------->  Q_R_4_0_62   mejora:  0.001796407185628679
Añadimos:  Q_R_4_0_72 , Resultado:  0.9766467065868264
-------------->  Q_R_4_0_72   mejora:  0.00119760479041919

Añadimos:  Q_R_4_1_02 , Resultado:  0.9772455089820359
Añadimos:  Q_G_3_0_02 , Resultado:  0.9778443113772455
Añadimos:  Q_G_3_0_12 , Resultado:  0.9802395209580839
-------------->  Q_G_3_0_12   mejora:  0.0005988023952095967
Añadimos:  Q_G_3_0_22 , Resultado:  0.9790419161676647
Añadimos:  Q_G_3_0_32 , Resultado:  0.9772455089820359
Añadimos:  Q_G_3_0_42 , Resultado:  0.9778443113772455
Añadimos:  Q_G_3_0_52 , Resultado:  0.9772455089820359
Añadimos:  Q_G_3_0_62 , Resultado:  0.9772455089820359
Añadimos:  Q_G_3_0_72 , Resultado:  0.9772455089820359
Añadimos:  Q_G_3_0_82 , Resultado:  0.9784431137724551
Añadimos:  Q_G_3_0_92 , Resultado:  0.9784431137724551
Añadimos:  Q_G_3_1_02 , Resultado:  0.9760479041916168
Añadimos:  Q_B_2_0_02 , Resultado:  0.9778443113772455
Añadimos:  Q_B_2_0_12 , Resultado:  0.9760479041916168
Añadimos:  Q_B_2_0_22 , Resultado:  0.9796407185628743
Añadimos:  Q_B_2_0_32 , Resultado:  0.9778443113772455
Añadimos:  Q_B_2_0_42 , Resultado:  0.9772455089820359
Añad

Eliminanmos:  Q_G_3_0_6
Eliminanmos:  Q_G_3_0_7
Eliminanmos:  Q_G_3_0_8
Eliminanmos:  Q_G_3_0_9
Eliminanmos:  Q_G_3_1_0
Eliminanmos:  Q_B_2_0_0
Eliminanmos:  Q_B_2_0_2
Eliminanmos:  Q_B_2_0_3
Eliminanmos:  Q_B_2_0_4
Eliminanmos:  Q_B_2_0_5
Eliminanmos:  Q_B_2_0_6
Eliminanmos:  Q_B_2_0_7
Eliminanmos:  Q_B_2_0_8
Eliminanmos:  Q_B_2_0_9
Eliminanmos:  Q_B_2_1_0
Eliminanmos:  Q_NIR_8_0_0
Eliminanmos:  Q_NIR_8_0_1
Eliminanmos:  Q_NIR_8_0_2
Eliminanmos:  Q_NIR_8_0_3
Eliminanmos:  Q_NIR_8_0_4
Eliminanmos:  Q_NIR_8_0_5
Eliminanmos:  Q_NIR_8_0_6
Eliminanmos:  Q_NIR_8_0_7
Eliminanmos:  Q_NIR_8_0_8
Eliminanmos:  Q_NIR_8_0_9
Eliminanmos:  Q_NIR_8_1_0
Eliminanmos:  AREA
Eliminanmos:  GEOM_R1
Eliminanmos:  GEOM_R2
Eliminanmos:  GEOM_R3
Eliminanmos:  GEOM_R4
Eliminanmos:  CONTRUCTIONYEAR
Eliminanmos:  MAXBUILDINGFLOOR
Eliminanmos:  CADASTRALQUALITYID


## AGRICULTURE vs INDUSTRIAL:

In [8]:
data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "INDUSTRIAL"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values
print(Counter(y))
print()
cv_results = cross_validate(RandomForestClassifier(n_jobs=-1), X, y, cv=3)
print(cv_results['test_score'])
cv_pred = cross_val_predict(RandomForestClassifier(n_jobs=-1), X, y, cv=3)
print(classification_report(y, cv_pred, digits=3))

Counter({'INDUSTRIAL': 4490, 'AGRICULTURE': 338})

[0.97080745 0.97762585 0.97513984]
              precision    recall  f1-score   support

 AGRICULTURE      0.846     0.766     0.804       338
  INDUSTRIAL      0.983     0.990     0.986      4490

    accuracy                          0.974      4828
   macro avg      0.914     0.878     0.895      4828
weighted avg      0.973     0.974     0.973      4828



In [9]:
data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "INDUSTRIAL"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values

model = RandomForestClassifier(n_jobs=-1)
feature_selection(data, labels, model)

data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "INDUS"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values

model = RandomForestClassifier(n_jobs=-1)
feature_square(data, labels, model)


Punto de partida(todas las características) 0.9763877381938691
Eliminanmos:  X
Eliminanmos:  Y
Eliminanmos:  Q_R_4_0_0
Eliminanmos:  Q_R_4_0_1
Eliminanmos:  Q_R_4_0_2
Eliminanmos:  Q_R_4_0_3
Eliminanmos:  Q_R_4_0_4
Eliminanmos:  Q_R_4_0_5
Eliminanmos:  Q_R_4_0_6
Eliminanmos:  Q_R_4_0_7
Eliminanmos:  Q_R_4_0_8
Eliminanmos:  Q_R_4_0_9
Eliminanmos:  Q_R_4_1_0
Eliminanmos:  Q_G_3_0_0
Eliminanmos:  Q_G_3_0_1
Eliminanmos:  Q_G_3_0_2
Eliminanmos:  Q_G_3_0_3
Eliminanmos:  Q_G_3_0_4
Eliminanmos:  Q_G_3_0_5
Eliminanmos:  Q_G_3_0_6
Eliminanmos:  Q_G_3_0_7
Eliminanmos:  Q_G_3_0_8
Eliminanmos:  Q_G_3_0_9
Eliminanmos:  Q_G_3_1_0
Q_G_3_1_0   mejora:  0.0006213753106876219
Eliminanmos:  Q_B_2_0_0
Eliminanmos:  Q_B_2_0_1
Eliminanmos:  Q_B_2_0_2
Eliminanmos:  Q_B_2_0_3
Q_B_2_0_3   mejora:  0.0002071251035624666
Eliminanmos:  Q_B_2_0_4
Eliminanmos:  Q_B_2_0_5
Eliminanmos:  Q_B_2_0_6
Eliminanmos:  Q_B_2_0_7
Eliminanmos:  Q_B_2_0_8
Eliminanmos:  Q_B_2_0_9
Eliminanmos:  Q_B_2_1_0
Eliminanmos:  Q_NIR_8_0_0
E

## AGRICULTURE vs RESIDENTIAL:

In [10]:
data = pd.concat([_data,_labels], axis=1)
data_1 = data[data.CLASE == "AGRICULTURE"]
data_2 = data[data.CLASE == "RESIDENTIAL"]
data = pd.concat([data_1, data_2])
labels = data.CLASE
data = data.drop('CLASE', axis=1)
X = data.values
y = labels.values
print(Counter(y))
print()
cv_results = cross_validate(RandomForestClassifier(n_jobs=-1), X, y, cv=3)
print(cv_results['test_score'])
cv_pred = cross_val_predict(RandomForestClassifier(n_jobs=-1), X, y, cv=3)
print(classification_report(y, cv_pred, digits=3))

Counter({'RESIDENTIAL': 90173, 'AGRICULTURE': 338})

[0.99827649 0.99867418 0.99864103]
              precision    recall  f1-score   support

 AGRICULTURE      0.902     0.707     0.793       338
 RESIDENTIAL      0.999     1.000     0.999     90173

    accuracy                          0.999     90511
   macro avg      0.950     0.853     0.896     90511
weighted avg      0.999     0.999     0.999     90511



In [4]:
def feature_selection(data,labels,model):
    X = data.values
    y = labels.values
    cv_pred = cross_val_predict(model, X, y, cv=5)
    best = accuracy_score(y, cv_pred)
    print("Punto de partida(todas las características)", best)

    mejoria = True

    while(mejoria == True):
        mejoria = False
        best_dict = {}
        for c in data:
            print("Eliminanmos: ",c)

            data_temp = data.copy()
            data_temp.drop(labels=[c], axis=1, inplace = True)

            X = data_temp.values
            cv_pred = cross_val_predict(model, X, y, cv=5)
            temp = accuracy_score(y, cv_pred)
            #temp = validacion_cruzada_sc(knn,X,y,skf)
            #print("-> Resultado: ",temp)

            if(temp > best):
                best_dict[(temp)] = c 
                print(c, "  mejora: ", (temp-best) )
                mejoria = True

        if (mejoria):
            # Obtenemos mayor valor:
            best = sorted(best_dict, reverse=True)[0]

            # Columna asociada a dicho valor:
            col =best_dict[best]

            # Eliminamos la columna correspondiente al valor maximo:
            data.drop(labels=[col], axis=1, inplace = True)
            print("=======> Eliminanmos: ",col, " -> score: ", best)

def feature_square(data,labels,model):       
    X = data.values
    y = labels.values
    cv_pred = cross_val_predict(model, X, y, cv=5)
    best = accuracy_score(y, cv_pred)
    print("Punto de partida(todas las características)", best)

    mejoria = True

    while(mejoria == True):
        mejoria = False
        best_dict = {}
        for c in data:
            #print("Eliminanmos: ",c)

            data_temp = data.copy()
            # Generamos la nueva variable (manteniendo el signo original)
            name = c+'2'
            data_temp[name] = data_temp[c]**2

            X = data_temp.values
        
            cv_pred = cross_val_predict(model, X, y, cv=5)
            temp = accuracy_score(y, cv_pred)
            print("Añadimos: ",name, ", Resultado: ",temp)

            if(temp > best):
                best_dict[(temp)] = c 
                print("--------------> ",name, "  mejora: ", (temp-best) )
                mejoria = True

        if (mejoria):
            # Obtenemos mayor valor:
            best = sorted(best_dict, reverse=True)[0]

            # Columna asociada a dicho valor:
            col =best_dict[best]

            # Añadimos la columna correspondiente al valor maximo:
            name = col+'2'
            data[name] = data[col]**2
           
            print("===========> Añadimos: ",name, " --------------> score: ", best)
            print(' ')